name: HuntingDoc-api dev CI

on:
  push:
    branches: [development]

jobs:
  api:
    name: API
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build in Target
        run: |
          cp -r build ${{secrets.TARGET_DIR_DEV}}
          cp -r node_modules ${{secrets.TARGET_DIR_DEV}}
