name: HuntingDoc-api prod CI

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build in Target
        run: |
          cp -r build ${{secrets.TARGET_DIR_PROD}}
          cp -r node_modules ${{secrets.TARGET_DIR_PROD}}
